// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qstqqvmacdqlfeajnccu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzdHFxdm1hY2RxbGZlYWpuY2N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNjM0MDEsImV4cCI6MjA3MzYzOTQwMX0.ycICaCGXISZqe6WsbB2_wOrBOXoI5SbsrBmSbMEkmoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});